# Generated by Django 5.0.6 on 2024-07-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
